import typography from '@tailwindcss/typography'
import animate from 'tailwindcss-animate'

/** @type {import('tailwindcss').Config} */
export default {
  content: ['./src/**/*.{ts,tsx}'],
  corePlugins: {
    preflight: false,
  },
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'ink-2': '#353330',
        'cat-politics-text': '#444263',
        'line': '#E1DDD5',
        'line-2': '#EEE9E7',
        'line-a08': '#E1DDD514',
        'ink': '#221E1D',
        'muted': '#5D554F',
        'muted-a16': '#5D554F29',
        'meta': '#7E7873',
        'date': '#7D7169',
        'muted-2': '#948E89',
        'muted-3': '#8A8683',
        'muted-4': '#6E6A67',
        'muted-5': '#605D5C',
        'gray-strong': '#5E5E5E',
        'sand': '#E8DFD8',
        'sand-a32': '#E8DFD852',
        'sand-2': '#E8E1DA',
        'sand-3': '#E8E0D8',
        'cream': '#F4F0ED',
        'paper': '#F7F4F2',
        'paper-2': '#F7F6F5',
        'paper-3': '#F7F5F2',
        'shell': '#F2ECE6',
        'shell-2': '#EFE8E1',
        'hover': '#FAF8F7',
        'placeholder': '#BAB2AD',
        'gray-soft': '#F1F1F1',
        'gray-softer': '#F9F9F9',
        'gray-border': '#E5E7EB',
        'gray-text': '#6B7280',
        'live': '#D7564F',
        'live-a24': '#D7564F3D',
        'live-a20': '#D7564F33',
        'live-soft': '#F7DDDC',
        'live-soft-2': '#F9E6E5',
        'danger': '#CF372F',
        'success': '#357B46',
        'success-a24': '#357B463D',
        'positive': '#57B96F',
        'negative': '#B95757',
        'info': '#4A83EC',
        'spread': '#B98D57',
        'white': '#FFFFFF',
        'white-a80': '#FFFFFFCC',
        'white-a56': '#FFFFFF8F',
        'white-a50': '#FFFFFF80',
        'white-a24': '#FFFFFF3D',
        'white-a12': '#FFFFFF1F',
        'cat-arb-bg': '#ECF2E0',
        'cat-arb-border': '#C6DB9E',
        'cat-arb-text': '#36581E',
        'cat-crypto-bg': '#FEFDF2',
        'cat-crypto-border': '#E9E9D1',
        'cat-crypto-text': '#655E4A',
        'cat-whale-bg': '#E8E0F2',
        'cat-whale-border': '#ADABE7',
        'cat-whale-text': '#3C3985',
        'cat-politics-bg': '#F0EFFE',
        'cat-politics-border': '#D4D2EA',
        'cat-tech-bg': '#FEF2F2',
        'cat-tech-border': '#E9D1D1',
        'cat-tech-text': '#654A4A',
        'cat-sports-bg': '#F2FEF3',
        'cat-sports-border': '#D1E9D4',
        'cat-sports-text': '#4A654F',
        'cat-science-bg': '#EBF5FF',
        'cat-science-border': '#C7DBEC',
        'cat-science-text': '#3B586F',
        'chip-bg': '#E0E8F5',
        'chip-border': '#CAD7ED',
        'blue': '#3B82F6',
        'developing': '#6B42D9',
        'developing-bg': '#F7F4F2',
        'amber': '#F59E0B',
        'red': '#EF4444',
        'green': '#10B981',
      },
      fontFamily: {
        sans: ['var(--font-sans)', 'system-ui', 'sans-serif'],
      },
      transitionTimingFunction: {
        smooth: 'cubic-bezier(0.16, 1, 0.3, 1)',
      },
      transitionDuration: {
        350: '350ms',
      },
    },
  },
  plugins: [typography, animate],
}
