/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    pages: Page;
    news: News;
    categories: Category;
    tags: Tag;
    signals: Signal;
    'live-feed': LiveFeed;
    authors: Author;
    ticker: Ticker;
    'contact-submissions': ContactSubmission;
    'newsletter-submissions': NewsletterSubmission;
    redirects: Redirect;
    search: Search;
    exports: Export;
    imports: Import;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    news: NewsSelect<false> | NewsSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    tags: TagsSelect<false> | TagsSelect<true>;
    signals: SignalsSelect<false> | SignalsSelect<true>;
    'live-feed': LiveFeedSelect<false> | LiveFeedSelect<true>;
    authors: AuthorsSelect<false> | AuthorsSelect<true>;
    ticker: TickerSelect<false> | TickerSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    'newsletter-submissions': NewsletterSubmissionsSelect<false> | NewsletterSubmissionsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'site-settings': SiteSetting;
    'home-page': HomePage;
    'about-page': AboutPage;
    'contact-page': ContactPage;
    'signals-page': SignalsPage;
    'live-feed-page': LiveFeedPage;
    'news-page': NewsPage;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'about-page': AboutPageSelect<false> | AboutPageSelect<true>;
    'contact-page': ContactPageSelect<false> | ContactPageSelect<true>;
    'signals-page': SignalsPageSelect<false> | SignalsPageSelect<true>;
    'live-feed-page': LiveFeedPageSelect<false> | LiveFeedPageSelect<true>;
    'news-page': NewsPageSelect<false> | NewsPageSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name?: string | null;
  role: 'admin' | 'editor';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt?: string | null;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    tablet?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  blocks?:
    | (
        | {
            heading: string;
            subheading?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            ctas?:
              | {
                  link: {
                    type?: ('reference' | 'custom') | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: string | Page;
                        } | null)
                      | ({
                          relationTo: 'news';
                          value: string | News;
                        } | null);
                    url?: string | null;
                    label: string;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            background?: {
              type?: ('none' | 'image' | 'video') | null;
              image?: (string | null) | Media;
              video?: (string | null) | Media;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'hero';
          }
        | {
            heading: string;
            description?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            buttons?:
              | {
                  link: {
                    type?: ('reference' | 'custom') | null;
                    reference?:
                      | ({
                          relationTo: 'pages';
                          value: string | Page;
                        } | null)
                      | ({
                          relationTo: 'news';
                          value: string | News;
                        } | null);
                    url?: string | null;
                    label: string;
                    newTab?: boolean | null;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'call-to-action';
          }
        | {
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            maxWidth?: ('prose' | 'wide' | 'full') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'rich-text-block';
          }
        | {
            heading?: string | null;
            content: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            };
            media?: {
              type?: ('image' | 'video') | null;
              image?: (string | null) | Media;
              video?: (string | null) | Media;
            };
            mediaPosition?: ('left' | 'right') | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'media-with-text';
          }
        | {
            heading?: string | null;
            sections?:
              | {
                  heading?: string | null;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  image?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'content-media';
          }
        | {
            heading?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  heading?: string | null;
                  content?: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  } | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text-columns';
          }
        | {
            heading?: string | null;
            subheading?: string | null;
            columns?: ('2' | '3' | '4') | null;
            items?:
              | {
                  icon?: (string | null) | Media;
                  title: string;
                  description?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'feature-grid';
          }
        | {
            heading?: string | null;
            columns?: ('2' | '3' | '4' | '6') | null;
            images?:
              | {
                  image: string | Media;
                  caption?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'image-grid';
          }
        | {
            heading?: string | null;
            logos?:
              | {
                  image: string | Media;
                  name?: string | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'logo-cloud';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  question: string;
                  answer: {
                    root: {
                      type: string;
                      children: {
                        type: any;
                        version: number;
                        [k: string]: unknown;
                      }[];
                      direction: ('ltr' | 'rtl') | null;
                      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                      indent: number;
                      version: number;
                    };
                    [k: string]: unknown;
                  };
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'faq';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  /**
                   * Numeric or formatted ("$2.4M", "+47%", "12,500")
                   */
                  value: string;
                  label: string;
                  description?: string | null;
                  animateCounter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats';
          }
        | {
            /**
             * Optional heading above the block, e.g. "Summary". Leave empty to hide.
             */
            title?: string | null;
            /**
             * Optional description text below the title.
             */
            subtitle?: string | null;
            /**
             * Default link for the "Read …" button, used by any tab without its own URL (defaults to the signals page).
             */
            buttonUrl?: string | null;
            /**
             * Default label for the button, used by any tab without its own text. Leave empty to fall back to "Read <tab title>".
             */
            buttonText?: string | null;
            /**
             * If there is only one, the tabs are not displayed on the site.
             */
            tabs?:
              | {
                  title: string;
                  infoTitle: string;
                  /**
                   * Where this tab's "Read …" button links. Leave empty to use the block-level default below.
                   */
                  buttonUrl?: string | null;
                  /**
                   * This tab's button label. Leave empty to use the block-level default, then "Read <tab title>".
                   */
                  buttonText?: string | null;
                  day?: string | null;
                  time?: string | null;
                  info?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'summary';
          }
        | {
            /**
             * Icon in the badge (e.g., Lightning)
             */
            badgeIcon: string | Media;
            badgeText: string;
            showLiveDot?: boolean | null;
            title: string;
            description: string;
            buttonText: string;
            /**
             * Where the button leads (optional; if left blank, there is no link)
             */
            buttonUrl?: string | null;
            /**
             * Decorative image (e.g., Graph)
             */
            backgroundImage: string | Media;
            /**
             * Card eases along with the page scroll once it enters the viewport (desktop only).
             */
            scrollFollow?: boolean | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-card';
          }
        | {
            heading?: string | null;
            items?:
              | {
                  quote: string;
                  author: string;
                  role?: string | null;
                  avatar?: (string | null) | Media;
                  id?: string | null;
                }[]
              | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'testimonials';
          }
        | {
            title?: string | null;
            description?: string | null;
            layout?: ('stats-and-chart' | 'chart-only' | 'stats-only') | null;
            stats?:
              | {
                  value: string;
                  label: string;
                  animateCounter?: boolean | null;
                  id?: string | null;
                }[]
              | null;
            chart?: {
              type?: ('line' | 'bar' | 'area' | 'donut') | null;
              xAxisLabel?: string | null;
              yAxisLabel?: string | null;
              series?:
                | {
                    name: string;
                    /**
                     * Hex color, e.g. #3b82f6
                     */
                    color?: string | null;
                    dataPoints?:
                      | {
                          label: string;
                          value: number;
                          id?: string | null;
                        }[]
                      | null;
                    id?: string | null;
                  }[]
                | null;
            };
            id?: string | null;
            blockName?: string | null;
            blockType: 'stats-chart';
          }
      )[]
    | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  /**
   * URL-friendly identifier (auto-generated from title if blank)
   */
  slug: string;
  parent?: (string | null) | Page;
  breadcrumbs?:
    | {
        doc?: (string | null) | Page;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news".
 */
export interface News {
  id: string;
  title: string;
  /**
   * Short summary, also used as the meta description fallback. Max 150 characters.
   */
  excerpt?: string | null;
  coverImage?: (string | null) | Media;
  /**
   * Surface in featured/grid slots.
   */
  featured?: boolean | null;
  /**
   * Show the live badge.
   */
  live?: boolean | null;
  /**
   * Show the developing badge.
   */
  isDeveloping?: boolean | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  author?: (string | null) | User;
  'author photo'?: (string | null) | Media;
  'author job'?: string | null;
  /**
   * Public author profile shown on the site (/author/[slug]).
   */
  authorProfile?: (string | null) | Author;
  categories?: (string | Category)[] | null;
  tags?: (string | Tag)[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  /**
   * URL-friendly identifier (auto-generated from title if blank)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors".
 */
export interface Author {
  id: string;
  name: string;
  role?: string | null;
  photo?: (string | null) | Media;
  bio?: string | null;
  social?:
    | {
        icon: string | Media;
        text?: string | null;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * URL-friendly identifier (auto-generated from name if blank)
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  description?: string | null;
  /**
   * URL-friendly identifier (auto-generated from title if blank)
   */
  slug: string;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags".
 */
export interface Tag {
  id: string;
  title: string;
  /**
   * URL-friendly identifier (auto-generated from title if blank)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals".
 */
export interface Signal {
  id: string;
  title: string;
  subtitle?: string | null;
  kind: 'arbitrage' | 'whale';
  featured?: boolean | null;
  coverImage?: (string | null) | Media;
  yesPrice?: string | null;
  noPrice?: string | null;
  yesVenue?: string | null;
  noVenue?: string | null;
  poly?: string | null;
  kalshi?: string | null;
  polyUrl?: string | null;
  kalshiUrl?: string | null;
  marketUrl?: string | null;
  side?: string | null;
  size?: string | null;
  odds?: string | null;
  spread?: string | null;
  platform?: string | null;
  address?: string | null;
  volume?: string | null;
  profitablyPP?: string | null;
  profitably?: boolean | null;
  externalId?: string | null;
  externalSource?: string | null;
  externalCreatedMs?: number | null;
  externalText?: string | null;
  categories?: (string | Category)[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  /**
   * URL-friendly identifier (auto-generated from title if blank)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-feed".
 */
export interface LiveFeed {
  id: string;
  title: string;
  subtitle?: string | null;
  coverImage?: (string | null) | Media;
  timeline?:
    | {
        /**
         * Manual label shown for this update (e.g. "Latest", "09:30").
         */
        time: string;
        /**
         * Optional update title.
         */
        heading?: string | null;
        image?: (string | null) | Media;
        body: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        };
        /**
         * Drives the "x minutes ago" label. Auto-set when the update is first added; edit to override.
         */
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  live?: boolean | null;
  /**
   * Update count badge.
   */
  updates?: number | null;
  categories?: (string | Category)[] | null;
  publishedAt?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
  };
  /**
   * URL-friendly identifier (auto-generated from title if blank)
   */
  slug: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticker".
 */
export interface Ticker {
  id: string;
  venue: 'Kalshi' | 'Polymarket';
  market: string;
  price: string;
  order?: number | null;
  url?: string | null;
  /**
   * Set by ticker-sync; empty = manually managed row
   */
  externalId?: string | null;
  volume24h?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: string;
  name: string;
  email: string;
  subject: string;
  message: string;
  /**
   * Captured automatically on submit.
   */
  metadata?: {
    ipAddress?: string | null;
    country?: string | null;
    city?: string | null;
    region?: string | null;
    /**
     * Referral source (document.referrer).
     */
    referrer?: string | null;
    /**
     * Page the form was submitted from.
     */
    landingUrl?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-submissions".
 */
export interface NewsletterSubmission {
  id: string;
  email: string;
  /**
   * Captured automatically on submit.
   */
  metadata?: {
    ipAddress?: string | null;
    country?: string | null;
    city?: string | null;
    region?: string | null;
    /**
     * Referral source (document.referrer).
     */
    referrer?: string | null;
    /**
     * Page the form was submitted from.
     */
    landingUrl?: string | null;
    userAgent?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'news';
          value: string | News;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc:
    | {
        relationTo: 'pages';
        value: string | Page;
      }
    | {
        relationTo: 'news';
        value: string | News;
      }
    | {
        relationTo: 'signals';
        value: string | Signal;
      }
    | {
        relationTo: 'live-feed';
        value: string | LiveFeed;
      };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: string;
  name?: string | null;
  format: 'csv' | 'json';
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ('asc' | 'desc') | null;
  drafts?: ('yes' | 'no') | null;
  selectionToUse?: ('currentSelection' | 'currentFilters' | 'all') | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: string;
  collectionSlug: string;
  importMode?: ('create' | 'update' | 'upsert') | null;
  matchField?: string | null;
  status?: ('pending' | 'completed' | 'partial' | 'failed') | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug: 'inline' | 'createCollectionExport' | 'createCollectionImport';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?: ('inline' | 'createCollectionExport' | 'createCollectionImport') | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'news';
        value: string | News;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'tags';
        value: string | Tag;
      } | null)
    | ({
        relationTo: 'signals';
        value: string | Signal;
      } | null)
    | ({
        relationTo: 'live-feed';
        value: string | LiveFeed;
      } | null)
    | ({
        relationTo: 'authors';
        value: string | Author;
      } | null)
    | ({
        relationTo: 'ticker';
        value: string | Ticker;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: string | ContactSubmission;
      } | null)
    | ({
        relationTo: 'newsletter-submissions';
        value: string | NewsletterSubmission;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        tablet?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  blocks?:
    | T
    | {
        hero?:
          | T
          | {
              heading?: T;
              subheading?: T;
              ctas?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              background?:
                | T
                | {
                    type?: T;
                    image?: T;
                    video?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'call-to-action'?:
          | T
          | {
              heading?: T;
              description?: T;
              buttons?:
                | T
                | {
                    link?:
                      | T
                      | {
                          type?: T;
                          reference?: T;
                          url?: T;
                          label?: T;
                          newTab?: T;
                        };
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'rich-text-block'?:
          | T
          | {
              content?: T;
              maxWidth?: T;
              id?: T;
              blockName?: T;
            };
        'media-with-text'?:
          | T
          | {
              heading?: T;
              content?: T;
              media?:
                | T
                | {
                    type?: T;
                    image?: T;
                    video?: T;
                  };
              mediaPosition?: T;
              id?: T;
              blockName?: T;
            };
        'content-media'?:
          | T
          | {
              heading?: T;
              sections?:
                | T
                | {
                    heading?: T;
                    content?: T;
                    image?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'text-columns'?:
          | T
          | {
              heading?: T;
              columns?: T;
              items?:
                | T
                | {
                    heading?: T;
                    content?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'feature-grid'?:
          | T
          | {
              heading?: T;
              subheading?: T;
              columns?: T;
              items?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    description?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'image-grid'?:
          | T
          | {
              heading?: T;
              columns?: T;
              images?:
                | T
                | {
                    image?: T;
                    caption?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'logo-cloud'?:
          | T
          | {
              heading?: T;
              logos?:
                | T
                | {
                    image?: T;
                    name?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        faq?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    question?: T;
                    answer?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        stats?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    value?: T;
                    label?: T;
                    description?: T;
                    animateCounter?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        summary?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonUrl?: T;
              buttonText?: T;
              tabs?:
                | T
                | {
                    title?: T;
                    infoTitle?: T;
                    buttonUrl?: T;
                    buttonText?: T;
                    day?: T;
                    time?: T;
                    info?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'real-card'?:
          | T
          | {
              badgeIcon?: T;
              badgeText?: T;
              showLiveDot?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              backgroundImage?: T;
              scrollFollow?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        testimonials?:
          | T
          | {
              heading?: T;
              items?:
                | T
                | {
                    quote?: T;
                    author?: T;
                    role?: T;
                    avatar?: T;
                    id?: T;
                  };
              id?: T;
              blockName?: T;
            };
        'stats-chart'?:
          | T
          | {
              title?: T;
              description?: T;
              layout?: T;
              stats?:
                | T
                | {
                    value?: T;
                    label?: T;
                    animateCounter?: T;
                    id?: T;
                  };
              chart?:
                | T
                | {
                    type?: T;
                    xAxisLabel?: T;
                    yAxisLabel?: T;
                    series?:
                      | T
                      | {
                          name?: T;
                          color?: T;
                          dataPoints?:
                            | T
                            | {
                                label?: T;
                                value?: T;
                                id?: T;
                              };
                          id?: T;
                        };
                  };
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news_select".
 */
export interface NewsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  coverImage?: T;
  featured?: T;
  live?: T;
  isDeveloping?: T;
  content?: T;
  author?: T;
  'author photo'?: T;
  'author job'?: T;
  authorProfile?: T;
  categories?: T;
  tags?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "tags_select".
 */
export interface TagsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals_select".
 */
export interface SignalsSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  kind?: T;
  featured?: T;
  coverImage?: T;
  yesPrice?: T;
  noPrice?: T;
  yesVenue?: T;
  noVenue?: T;
  poly?: T;
  kalshi?: T;
  polyUrl?: T;
  kalshiUrl?: T;
  marketUrl?: T;
  side?: T;
  size?: T;
  odds?: T;
  spread?: T;
  platform?: T;
  address?: T;
  volume?: T;
  profitablyPP?: T;
  profitably?: T;
  externalId?: T;
  externalSource?: T;
  externalCreatedMs?: T;
  externalText?: T;
  categories?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-feed_select".
 */
export interface LiveFeedSelect<T extends boolean = true> {
  title?: T;
  subtitle?: T;
  coverImage?: T;
  timeline?:
    | T
    | {
        time?: T;
        heading?: T;
        image?: T;
        body?: T;
        at?: T;
        id?: T;
      };
  live?: T;
  updates?: T;
  categories?: T;
  publishedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "authors_select".
 */
export interface AuthorsSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  photo?: T;
  bio?: T;
  social?:
    | T
    | {
        icon?: T;
        text?: T;
        url?: T;
        id?: T;
      };
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ticker_select".
 */
export interface TickerSelect<T extends boolean = true> {
  venue?: T;
  market?: T;
  price?: T;
  order?: T;
  url?: T;
  externalId?: T;
  volume24h?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  subject?: T;
  message?: T;
  metadata?:
    | T
    | {
        ipAddress?: T;
        country?: T;
        city?: T;
        region?: T;
        referrer?: T;
        landingUrl?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-submissions_select".
 */
export interface NewsletterSubmissionsSelect<T extends boolean = true> {
  email?: T;
  metadata?:
    | T
    | {
        ipAddress?: T;
        country?: T;
        city?: T;
        region?: T;
        referrer?: T;
        landingUrl?: T;
        userAgent?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  logo?: (string | null) | Media;
  brandName?: string | null;
  nav?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'news';
                value: string | News;
              } | null);
          url?: string | null;
          label: string;
          newTab?: boolean | null;
        };
        children?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'news';
                      value: string | News;
                    } | null);
                url?: string | null;
                label: string;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  cta?: {
    label?: string | null;
    href?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  brandName?: string | null;
  tagline?: string | null;
  columns?:
    | {
        title?: string | null;
        items?:
          | {
              link: {
                type?: ('reference' | 'custom') | null;
                reference?:
                  | ({
                      relationTo: 'pages';
                      value: string | Page;
                    } | null)
                  | ({
                      relationTo: 'news';
                      value: string | News;
                    } | null);
                url?: string | null;
                label: string;
                newTab?: boolean | null;
              };
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  disclaimer?: string | null;
  copyright?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: string;
  /**
   * Site name shown in the browser tab and the title suffix (e.g. "Page | Site Name"). Falls back to the built-in default when empty.
   */
  siteName?: string | null;
  /**
   * Site-wide favicon shown in browser tabs. Use a square .ico, .png, or .svg (32×32 or larger).
   */
  favicon?: (string | null) | Media;
  /**
   * Site-wide default meta description for search results and social shares. Used on every page that has no description of its own.
   */
  defaultMetaDescription?: string | null;
  /**
   * Site-wide default Open Graph / social share image (recommended 1200×630). Used on every page that has no image of its own.
   */
  defaultMetaImage?: (string | null) | Media;
  /**
   * Include published news posts in sitemap.xml.
   */
  sitemapIncludeNews?: boolean | null;
  /**
   * Include published signals in sitemap.xml.
   */
  sitemapIncludeSignals?: boolean | null;
  /**
   * Include published live feed threads in sitemap.xml.
   */
  sitemapIncludeLiveFeed?: boolean | null;
  /**
   * Block all crawlers (robots.txt Disallow: /). Use for staging.
   */
  robotsDisallowAll?: boolean | null;
  /**
   * Google Search Console verification token. In GSC, add a URL-prefix property and choose the "HTML tag" method — paste only the content value here (not the whole meta tag).
   */
  googleSiteVerification?: string | null;
  /**
   * Bing Webmaster Tools verification token (msvalidate.01 meta content).
   */
  bingSiteVerification?: string | null;
  /**
   * Google Tag Manager container ID (GTM-XXXXXXX).
   */
  gtmId?: string | null;
  /**
   * GA4 Measurement ID (G-XXXXXXXXXX).
   */
  ga4Id?: string | null;
  social?:
    | {
        icon: string | Media;
        url?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Promo card shown on all news sub-pages.
   */
  promoBlocks?:
    | {
        /**
         * Icon in the badge (e.g., Lightning)
         */
        badgeIcon: string | Media;
        badgeText: string;
        showLiveDot?: boolean | null;
        title: string;
        description: string;
        buttonText: string;
        /**
         * Where the button leads (optional; if left blank, there is no link)
         */
        buttonUrl?: string | null;
        /**
         * Decorative image (e.g., Graph)
         */
        backgroundImage: string | Media;
        /**
         * Card eases along with the page scroll once it enters the viewport (desktop only).
         */
        scrollFollow?: boolean | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'real-card';
      }[]
    | null;
  /**
   * Sponsored logos card shown on news article pages only.
   */
  sponsoredBlocks?:
    | {
        heading: string;
        infoIcon?: (string | null) | Media;
        sponsors?:
          | {
              logo: string | Media;
              id?: string | null;
            }[]
          | null;
        footerText?: string | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'sponsored-card';
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: string;
  signalsMobileHeader: {
    title: string;
    subtitle?: string | null;
  };
  /**
   * Whale Alert, Arbitrage Alert, Summaries, Promo card.
   */
  sidebarBlocks?:
    | (
        | {
            /**
             * On-site title, e.g. "Whale Alert" or "Arbitrage Alert".
             */
            heading: string;
            /**
             * Which signals to pull from the Signals collection.
             */
            kind: 'whale' | 'arbitrage';
            delayLabel?: string | null;
            limit?: number | null;
            viewAllText: string;
            viewAllUrl?: string | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'signal-feed';
          }
        | {
            /**
             * Optional heading above the block, e.g. "Summary". Leave empty to hide.
             */
            title?: string | null;
            /**
             * Optional description text below the title.
             */
            subtitle?: string | null;
            /**
             * Default link for the "Read …" button, used by any tab without its own URL (defaults to the signals page).
             */
            buttonUrl?: string | null;
            /**
             * Default label for the button, used by any tab without its own text. Leave empty to fall back to "Read <tab title>".
             */
            buttonText?: string | null;
            /**
             * If there is only one, the tabs are not displayed on the site.
             */
            tabs?:
              | {
                  title: string;
                  infoTitle: string;
                  /**
                   * Where this tab's "Read …" button links. Leave empty to use the block-level default below.
                   */
                  buttonUrl?: string | null;
                  /**
                   * This tab's button label. Leave empty to use the block-level default, then "Read <tab title>".
                   */
                  buttonText?: string | null;
                  day?: string | null;
                  time?: string | null;
                  info?:
                    | {
                        text: string;
                        id?: string | null;
                      }[]
                    | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'summary';
          }
        | {
            /**
             * Icon in the badge (e.g., Lightning)
             */
            badgeIcon: string | Media;
            badgeText: string;
            showLiveDot?: boolean | null;
            title: string;
            description: string;
            buttonText: string;
            /**
             * Where the button leads (optional; if left blank, there is no link)
             */
            buttonUrl?: string | null;
            /**
             * Decorative image (e.g., Graph)
             */
            backgroundImage: string | Media;
            /**
             * Card eases along with the page scroll once it enters the viewport (desktop only).
             */
            scrollFollow?: boolean | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-card';
          }
      )[]
    | null;
  categorySwitcherHeader: {
    title: string;
    subtitle?: string | null;
  };
  /**
   * Analysis, Live Feed, Category sections.
   */
  mainBlocks?:
    | (
        | {
            heading: string;
            subtitle?: string | null;
            limit?: number | null;
            viewAllText: string;
            viewAllUrl?: string | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'analysis';
          }
        | {
            heading: string;
            limit?: number | null;
            viewAllText: string;
            viewAllUrl?: string | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'live-feed-block';
          }
        | {
            /**
             * Row heading, e.g. "Politics".
             */
            label: string;
            category: string | Category;
            /**
             * Badge color theme for this row.
             */
            accent: 'politics' | 'sports' | 'crypto' | 'tech' | 'science';
            limit?: number | null;
            viewAllText: string;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'category-section';
          }
      )[]
    | null;
  meta?: {
    /**
     * Browser tab / search title. Falls back to the page heading.
     */
    title?: string | null;
    /**
     * Meta description for search engines and social shares.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (recommended 1200×630).
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page".
 */
export interface AboutPage {
  id: string;
  title?: string | null;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  cta?: {
    heading?: string | null;
    text?: string | null;
    embedUrl?: string | null;
  };
  sidebarBlocks?:
    | (
        | {
            heading: string;
            limit?: number | null;
            viewAllText: string;
            viewAllUrl?: string | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'live-feed-block';
          }
        | {
            /**
             * Icon in the badge (e.g., Lightning)
             */
            badgeIcon: string | Media;
            badgeText: string;
            showLiveDot?: boolean | null;
            title: string;
            description: string;
            buttonText: string;
            /**
             * Where the button leads (optional; if left blank, there is no link)
             */
            buttonUrl?: string | null;
            /**
             * Decorative image (e.g., Graph)
             */
            backgroundImage: string | Media;
            /**
             * Card eases along with the page scroll once it enters the viewport (desktop only).
             */
            scrollFollow?: boolean | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'real-card';
          }
      )[]
    | null;
  meta?: {
    /**
     * Browser tab / search title. Falls back to the page heading.
     */
    title?: string | null;
    /**
     * Meta description for search engines and social shares.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (recommended 1200×630).
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page".
 */
export interface ContactPage {
  id: string;
  mainBlocks?:
    | {
        heading?: string | null;
        subtitle?: string | null;
        subjectOptions?:
          | {
              label: string;
              /**
               * Mailbox this subject is emailed to. Falls back to the default recipient.
               */
              routeTo?: string | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Mailbox used when a subject has no specific route.
         */
        defaultRecipient?: string | null;
        nameLabel?: string | null;
        emailLabel?: string | null;
        subjectLabel?: string | null;
        messageLabel?: string | null;
        buttonText?: string | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'contact-form-fields';
      }[]
    | null;
  sidebarBlocks?:
    | (
        | {
            heading?: string | null;
            socialsHeading?: string | null;
            methods?:
              | {
                  icon?: (string | null) | Media;
                  title: string;
                  linkText: string;
                  link?: string | null;
                  id?: string | null;
                }[]
              | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-methods';
          }
        | {
            title?: string | null;
            text?: string | null;
            buttonText?: string | null;
            /**
             * Temporarily hide this block without deleting it.
             */
            hidden?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'contact-value';
          }
      )[]
    | null;
  meta?: {
    /**
     * Browser tab / search title. Falls back to the page heading.
     */
    title?: string | null;
    /**
     * Meta description for search engines and social shares.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (recommended 1200×630).
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals-page".
 */
export interface SignalsPage {
  id: string;
  mainBlocks?:
    | {
        heading: string;
        subtitle?: string | null;
        delayText?: string | null;
        limit?: number | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'signals-list';
      }[]
    | null;
  sidebarBlocks?:
    | {
        /**
         * Icon in the badge (e.g., Lightning)
         */
        badgeIcon: string | Media;
        badgeText: string;
        showLiveDot?: boolean | null;
        title: string;
        description: string;
        buttonText: string;
        /**
         * Where the button leads (optional; if left blank, there is no link)
         */
        buttonUrl?: string | null;
        /**
         * Decorative image (e.g., Graph)
         */
        backgroundImage: string | Media;
        /**
         * Card eases along with the page scroll once it enters the viewport (desktop only).
         */
        scrollFollow?: boolean | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'real-card';
      }[]
    | null;
  meta?: {
    /**
     * Browser tab / search title. Falls back to the page heading.
     */
    title?: string | null;
    /**
     * Meta description for search engines and social shares.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (recommended 1200×630).
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-feed-page".
 */
export interface LiveFeedPage {
  id: string;
  mainBlocks?:
    | {
        heading: string;
        subtitle?: string | null;
        limit?: number | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'live-feed-list';
      }[]
    | null;
  sidebarBlocks?:
    | {
        /**
         * Icon in the badge (e.g., Lightning)
         */
        badgeIcon: string | Media;
        badgeText: string;
        showLiveDot?: boolean | null;
        title: string;
        description: string;
        buttonText: string;
        /**
         * Where the button leads (optional; if left blank, there is no link)
         */
        buttonUrl?: string | null;
        /**
         * Decorative image (e.g., Graph)
         */
        backgroundImage: string | Media;
        /**
         * Card eases along with the page scroll once it enters the viewport (desktop only).
         */
        scrollFollow?: boolean | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'real-card';
      }[]
    | null;
  meta?: {
    /**
     * Browser tab / search title. Falls back to the page heading.
     */
    title?: string | null;
    /**
     * Meta description for search engines and social shares.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (recommended 1200×630).
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page".
 */
export interface NewsPage {
  id: string;
  mainBlocks?:
    | {
        heading: string;
        subtitle?: string | null;
        /**
         * Category filter buttons shown above the list.
         */
        categories?:
          | {
              title: string;
              id?: string | null;
            }[]
          | null;
        limit?: number | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'news-list';
      }[]
    | null;
  sidebarBlocks?:
    | {
        /**
         * Optional heading above the block, e.g. "Summary". Leave empty to hide.
         */
        title?: string | null;
        /**
         * Optional description text below the title.
         */
        subtitle?: string | null;
        /**
         * Default link for the "Read …" button, used by any tab without its own URL (defaults to the signals page).
         */
        buttonUrl?: string | null;
        /**
         * Default label for the button, used by any tab without its own text. Leave empty to fall back to "Read <tab title>".
         */
        buttonText?: string | null;
        /**
         * If there is only one, the tabs are not displayed on the site.
         */
        tabs?:
          | {
              title: string;
              infoTitle: string;
              /**
               * Where this tab's "Read …" button links. Leave empty to use the block-level default below.
               */
              buttonUrl?: string | null;
              /**
               * This tab's button label. Leave empty to use the block-level default, then "Read <tab title>".
               */
              buttonText?: string | null;
              day?: string | null;
              time?: string | null;
              info?:
                | {
                    text: string;
                    id?: string | null;
                  }[]
                | null;
              id?: string | null;
            }[]
          | null;
        /**
         * Temporarily hide this block without deleting it.
         */
        hidden?: boolean | null;
        id?: string | null;
        blockName?: string | null;
        blockType: 'summary';
      }[]
    | null;
  meta?: {
    /**
     * Browser tab / search title. Falls back to the page heading.
     */
    title?: string | null;
    /**
     * Meta description for search engines and social shares.
     */
    description?: string | null;
    /**
     * Open Graph / social share image (recommended 1200×630).
     */
    image?: (string | null) | Media;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  logo?: T;
  brandName?: T;
  nav?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              reference?: T;
              url?: T;
              label?: T;
              newTab?: T;
            };
        children?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  cta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  brandName?: T;
  tagline?: T;
  columns?:
    | T
    | {
        title?: T;
        items?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    newTab?: T;
                  };
              id?: T;
            };
        id?: T;
      };
  disclaimer?: T;
  copyright?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  favicon?: T;
  defaultMetaDescription?: T;
  defaultMetaImage?: T;
  sitemapIncludeNews?: T;
  sitemapIncludeSignals?: T;
  sitemapIncludeLiveFeed?: T;
  robotsDisallowAll?: T;
  googleSiteVerification?: T;
  bingSiteVerification?: T;
  gtmId?: T;
  ga4Id?: T;
  social?:
    | T
    | {
        icon?: T;
        url?: T;
        id?: T;
      };
  promoBlocks?:
    | T
    | {
        'real-card'?:
          | T
          | {
              badgeIcon?: T;
              badgeText?: T;
              showLiveDot?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              backgroundImage?: T;
              scrollFollow?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  sponsoredBlocks?:
    | T
    | {
        'sponsored-card'?:
          | T
          | {
              heading?: T;
              infoIcon?: T;
              sponsors?:
                | T
                | {
                    logo?: T;
                    id?: T;
                  };
              footerText?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  signalsMobileHeader?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  sidebarBlocks?:
    | T
    | {
        'signal-feed'?:
          | T
          | {
              heading?: T;
              kind?: T;
              delayLabel?: T;
              limit?: T;
              viewAllText?: T;
              viewAllUrl?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        summary?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonUrl?: T;
              buttonText?: T;
              tabs?:
                | T
                | {
                    title?: T;
                    infoTitle?: T;
                    buttonUrl?: T;
                    buttonText?: T;
                    day?: T;
                    time?: T;
                    info?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'real-card'?:
          | T
          | {
              badgeIcon?: T;
              badgeText?: T;
              showLiveDot?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              backgroundImage?: T;
              scrollFollow?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  categorySwitcherHeader?:
    | T
    | {
        title?: T;
        subtitle?: T;
      };
  mainBlocks?:
    | T
    | {
        analysis?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              limit?: T;
              viewAllText?: T;
              viewAllUrl?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'live-feed-block'?:
          | T
          | {
              heading?: T;
              limit?: T;
              viewAllText?: T;
              viewAllUrl?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'category-section'?:
          | T
          | {
              label?: T;
              category?: T;
              accent?: T;
              limit?: T;
              viewAllText?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "about-page_select".
 */
export interface AboutPageSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  cta?:
    | T
    | {
        heading?: T;
        text?: T;
        embedUrl?: T;
      };
  sidebarBlocks?:
    | T
    | {
        'live-feed-block'?:
          | T
          | {
              heading?: T;
              limit?: T;
              viewAllText?: T;
              viewAllUrl?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'real-card'?:
          | T
          | {
              badgeIcon?: T;
              badgeText?: T;
              showLiveDot?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              backgroundImage?: T;
              scrollFollow?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-page_select".
 */
export interface ContactPageSelect<T extends boolean = true> {
  mainBlocks?:
    | T
    | {
        'contact-form-fields'?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              subjectOptions?:
                | T
                | {
                    label?: T;
                    routeTo?: T;
                    id?: T;
                  };
              defaultRecipient?: T;
              nameLabel?: T;
              emailLabel?: T;
              subjectLabel?: T;
              messageLabel?: T;
              buttonText?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  sidebarBlocks?:
    | T
    | {
        'contact-methods'?:
          | T
          | {
              heading?: T;
              socialsHeading?: T;
              methods?:
                | T
                | {
                    icon?: T;
                    title?: T;
                    linkText?: T;
                    link?: T;
                    id?: T;
                  };
              hidden?: T;
              id?: T;
              blockName?: T;
            };
        'contact-value'?:
          | T
          | {
              title?: T;
              text?: T;
              buttonText?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "signals-page_select".
 */
export interface SignalsPageSelect<T extends boolean = true> {
  mainBlocks?:
    | T
    | {
        'signals-list'?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              delayText?: T;
              limit?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  sidebarBlocks?:
    | T
    | {
        'real-card'?:
          | T
          | {
              badgeIcon?: T;
              badgeText?: T;
              showLiveDot?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              backgroundImage?: T;
              scrollFollow?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "live-feed-page_select".
 */
export interface LiveFeedPageSelect<T extends boolean = true> {
  mainBlocks?:
    | T
    | {
        'live-feed-list'?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              limit?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  sidebarBlocks?:
    | T
    | {
        'real-card'?:
          | T
          | {
              badgeIcon?: T;
              badgeText?: T;
              showLiveDot?: T;
              title?: T;
              description?: T;
              buttonText?: T;
              buttonUrl?: T;
              backgroundImage?: T;
              scrollFollow?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "news-page_select".
 */
export interface NewsPageSelect<T extends boolean = true> {
  mainBlocks?:
    | T
    | {
        'news-list'?:
          | T
          | {
              heading?: T;
              subtitle?: T;
              categories?:
                | T
                | {
                    title?: T;
                    id?: T;
                  };
              limit?: T;
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  sidebarBlocks?:
    | T
    | {
        summary?:
          | T
          | {
              title?: T;
              subtitle?: T;
              buttonUrl?: T;
              buttonText?: T;
              tabs?:
                | T
                | {
                    title?: T;
                    infoTitle?: T;
                    buttonUrl?: T;
                    buttonText?: T;
                    day?: T;
                    time?: T;
                    info?:
                      | T
                      | {
                          text?: T;
                          id?: T;
                        };
                    id?: T;
                  };
              hidden?: T;
              id?: T;
              blockName?: T;
            };
      };
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | 'users'
      | 'media'
      | 'pages'
      | 'news'
      | 'categories'
      | 'tags'
      | 'signals'
      | 'live-feed'
      | 'authors'
      | 'ticker'
      | 'contact-submissions'
      | 'newsletter-submissions'
      | 'redirects'
      | 'search'
      | 'exports'
      | 'imports';
    drafts?: ('yes' | 'no') | null;
    exportCollection: string;
    fields?: string[] | null;
    format: 'csv' | 'json';
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ('draft' | 'published') | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}